#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_Cua_Hang_Chan_ga_Goi_Nem.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Changagoinem")]
	public partial class DataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertchi_tiet_khuyen_mai(chi_tiet_khuyen_mai instance);
    partial void Updatechi_tiet_khuyen_mai(chi_tiet_khuyen_mai instance);
    partial void Deletechi_tiet_khuyen_mai(chi_tiet_khuyen_mai instance);
    partial void Insertchi_tiet_san_pham(chi_tiet_san_pham instance);
    partial void Updatechi_tiet_san_pham(chi_tiet_san_pham instance);
    partial void Deletechi_tiet_san_pham(chi_tiet_san_pham instance);
    partial void Insertdanh_gia(danh_gia instance);
    partial void Updatedanh_gia(danh_gia instance);
    partial void Deletedanh_gia(danh_gia instance);
    partial void Inserthoa_don(hoa_don instance);
    partial void Updatehoa_don(hoa_don instance);
    partial void Deletehoa_don(hoa_don instance);
    partial void Insertkhuyen_mai(khuyen_mai instance);
    partial void Updatekhuyen_mai(khuyen_mai instance);
    partial void Deletekhuyen_mai(khuyen_mai instance);
    partial void Insertlog_thong_tin_hoa_don(log_thong_tin_hoa_don instance);
    partial void Updatelog_thong_tin_hoa_don(log_thong_tin_hoa_don instance);
    partial void Deletelog_thong_tin_hoa_don(log_thong_tin_hoa_don instance);
    partial void Insertnguoi_dung(nguoi_dung instance);
    partial void Updatenguoi_dung(nguoi_dung instance);
    partial void Deletenguoi_dung(nguoi_dung instance);
    partial void Insertsan_pham(san_pham instance);
    partial void Updatesan_pham(san_pham instance);
    partial void Deletesan_pham(san_pham instance);
    partial void Insertthanh_toan(thanh_toan instance);
    partial void Updatethanh_toan(thanh_toan instance);
    partial void Deletethanh_toan(thanh_toan instance);
    partial void Insertthong_bao(thong_bao instance);
    partial void Updatethong_bao(thong_bao instance);
    partial void Deletethong_bao(thong_bao instance);
    partial void Insertthong_bao_nguoi_dung(thong_bao_nguoi_dung instance);
    partial void Updatethong_bao_nguoi_dung(thong_bao_nguoi_dung instance);
    partial void Deletethong_bao_nguoi_dung(thong_bao_nguoi_dung instance);
    partial void Insertchi_tiet_hoa_don(chi_tiet_hoa_don instance);
    partial void Updatechi_tiet_hoa_don(chi_tiet_hoa_don instance);
    partial void Deletechi_tiet_hoa_don(chi_tiet_hoa_don instance);
    #endregion
		
		public DataDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ChangagoinemConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataDataContext(string connection) : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ChangagoinemConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<chi_tiet_khuyen_mai> chi_tiet_khuyen_mais
		{
			get
			{
				return this.GetTable<chi_tiet_khuyen_mai>();
			}
		}
		
		public System.Data.Linq.Table<chi_tiet_san_pham> chi_tiet_san_phams
		{
			get
			{
				return this.GetTable<chi_tiet_san_pham>();
			}
		}
		
		public System.Data.Linq.Table<danh_gia> danh_gias
		{
			get
			{
				return this.GetTable<danh_gia>();
			}
		}
		
		public System.Data.Linq.Table<hoa_don> hoa_dons
		{
			get
			{
				return this.GetTable<hoa_don>();
			}
		}
		
		public System.Data.Linq.Table<khuyen_mai> khuyen_mais
		{
			get
			{
				return this.GetTable<khuyen_mai>();
			}
		}
		
		public System.Data.Linq.Table<log_thong_tin_hoa_don> log_thong_tin_hoa_dons
		{
			get
			{
				return this.GetTable<log_thong_tin_hoa_don>();
			}
		}
		
		public System.Data.Linq.Table<nguoi_dung> nguoi_dungs
		{
			get
			{
				return this.GetTable<nguoi_dung>();
			}
		}
		
		public System.Data.Linq.Table<san_pham> san_phams
		{
			get
			{
				return this.GetTable<san_pham>();
			}
		}
		
		public System.Data.Linq.Table<thanh_toan> thanh_toans
		{
			get
			{
				return this.GetTable<thanh_toan>();
			}
		}
		
		public System.Data.Linq.Table<thong_bao> thong_baos
		{
			get
			{
				return this.GetTable<thong_bao>();
			}
		}
		
		public System.Data.Linq.Table<thong_bao_nguoi_dung> thong_bao_nguoi_dungs
		{
			get
			{
				return this.GetTable<thong_bao_nguoi_dung>();
			}
		}
		
		public System.Data.Linq.Table<chi_tiet_hoa_don> chi_tiet_hoa_dons
		{
			get
			{
				return this.GetTable<chi_tiet_hoa_don>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.chi_tiet_khuyen_mai")]
	public partial class chi_tiet_khuyen_mai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _chi_tiet_id;
		
		private System.Nullable<int> _khuyen_mai_id;
		
		private System.Nullable<int> _san_pham_id;
		
		private EntityRef<khuyen_mai> _khuyen_mai;
		
		private EntityRef<san_pham> _san_pham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onchi_tiet_idChanging(int value);
    partial void Onchi_tiet_idChanged();
    partial void Onkhuyen_mai_idChanging(System.Nullable<int> value);
    partial void Onkhuyen_mai_idChanged();
    partial void Onsan_pham_idChanging(System.Nullable<int> value);
    partial void Onsan_pham_idChanged();
    #endregion
		
		public chi_tiet_khuyen_mai()
		{
			this._khuyen_mai = default(EntityRef<khuyen_mai>);
			this._san_pham = default(EntityRef<san_pham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chi_tiet_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int chi_tiet_id
		{
			get
			{
				return this._chi_tiet_id;
			}
			set
			{
				if ((this._chi_tiet_id != value))
				{
					this.Onchi_tiet_idChanging(value);
					this.SendPropertyChanging();
					this._chi_tiet_id = value;
					this.SendPropertyChanged("chi_tiet_id");
					this.Onchi_tiet_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_khuyen_mai_id", DbType="Int")]
		public System.Nullable<int> khuyen_mai_id
		{
			get
			{
				return this._khuyen_mai_id;
			}
			set
			{
				if ((this._khuyen_mai_id != value))
				{
					if (this._khuyen_mai.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onkhuyen_mai_idChanging(value);
					this.SendPropertyChanging();
					this._khuyen_mai_id = value;
					this.SendPropertyChanged("khuyen_mai_id");
					this.Onkhuyen_mai_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_san_pham_id", DbType="Int")]
		public System.Nullable<int> san_pham_id
		{
			get
			{
				return this._san_pham_id;
			}
			set
			{
				if ((this._san_pham_id != value))
				{
					if (this._san_pham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onsan_pham_idChanging(value);
					this.SendPropertyChanging();
					this._san_pham_id = value;
					this.SendPropertyChanged("san_pham_id");
					this.Onsan_pham_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khuyen_mai_chi_tiet_khuyen_mai", Storage="_khuyen_mai", ThisKey="khuyen_mai_id", OtherKey="khuyen_mai_id", IsForeignKey=true)]
		public khuyen_mai khuyen_mai
		{
			get
			{
				return this._khuyen_mai.Entity;
			}
			set
			{
				khuyen_mai previousValue = this._khuyen_mai.Entity;
				if (((previousValue != value) 
							|| (this._khuyen_mai.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._khuyen_mai.Entity = null;
						previousValue.chi_tiet_khuyen_mais.Remove(this);
					}
					this._khuyen_mai.Entity = value;
					if ((value != null))
					{
						value.chi_tiet_khuyen_mais.Add(this);
						this._khuyen_mai_id = value.khuyen_mai_id;
					}
					else
					{
						this._khuyen_mai_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("khuyen_mai");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="san_pham_chi_tiet_khuyen_mai", Storage="_san_pham", ThisKey="san_pham_id", OtherKey="san_pham_id", IsForeignKey=true)]
		public san_pham san_pham
		{
			get
			{
				return this._san_pham.Entity;
			}
			set
			{
				san_pham previousValue = this._san_pham.Entity;
				if (((previousValue != value) 
							|| (this._san_pham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._san_pham.Entity = null;
						previousValue.chi_tiet_khuyen_mais.Remove(this);
					}
					this._san_pham.Entity = value;
					if ((value != null))
					{
						value.chi_tiet_khuyen_mais.Add(this);
						this._san_pham_id = value.san_pham_id;
					}
					else
					{
						this._san_pham_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("san_pham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.chi_tiet_san_pham")]
	public partial class chi_tiet_san_pham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _chi_tiet_id;
		
		private System.Nullable<int> _san_pham_id;
		
		private string _kich_thuoc;
		
		private System.Nullable<int> _do_day;
		
		private string _mau_sac;
		
		private string _chat_lieu;
		
		private System.Nullable<decimal> _gia;
		
		private System.Nullable<decimal> _gia_khuyen_mai;
		
		private System.Nullable<int> _so_luong_ton;
		
		private EntitySet<chi_tiet_hoa_don> _chi_tiet_hoa_dons;
		
		private EntityRef<san_pham> _san_pham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onchi_tiet_idChanging(int value);
    partial void Onchi_tiet_idChanged();
    partial void Onsan_pham_idChanging(System.Nullable<int> value);
    partial void Onsan_pham_idChanged();
    partial void Onkich_thuocChanging(string value);
    partial void Onkich_thuocChanged();
    partial void Ondo_dayChanging(System.Nullable<int> value);
    partial void Ondo_dayChanged();
    partial void Onmau_sacChanging(string value);
    partial void Onmau_sacChanged();
    partial void Onchat_lieuChanging(string value);
    partial void Onchat_lieuChanged();
    partial void OngiaChanging(System.Nullable<decimal> value);
    partial void OngiaChanged();
    partial void Ongia_khuyen_maiChanging(System.Nullable<decimal> value);
    partial void Ongia_khuyen_maiChanged();
    partial void Onso_luong_tonChanging(System.Nullable<int> value);
    partial void Onso_luong_tonChanged();
    #endregion
		
		public chi_tiet_san_pham()
		{
			this._chi_tiet_hoa_dons = new EntitySet<chi_tiet_hoa_don>(new Action<chi_tiet_hoa_don>(this.attach_chi_tiet_hoa_dons), new Action<chi_tiet_hoa_don>(this.detach_chi_tiet_hoa_dons));
			this._san_pham = default(EntityRef<san_pham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chi_tiet_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int chi_tiet_id
		{
			get
			{
				return this._chi_tiet_id;
			}
			set
			{
				if ((this._chi_tiet_id != value))
				{
					this.Onchi_tiet_idChanging(value);
					this.SendPropertyChanging();
					this._chi_tiet_id = value;
					this.SendPropertyChanged("chi_tiet_id");
					this.Onchi_tiet_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_san_pham_id", DbType="Int")]
		public System.Nullable<int> san_pham_id
		{
			get
			{
				return this._san_pham_id;
			}
			set
			{
				if ((this._san_pham_id != value))
				{
					if (this._san_pham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onsan_pham_idChanging(value);
					this.SendPropertyChanging();
					this._san_pham_id = value;
					this.SendPropertyChanged("san_pham_id");
					this.Onsan_pham_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kich_thuoc", DbType="NVarChar(255)")]
		public string kich_thuoc
		{
			get
			{
				return this._kich_thuoc;
			}
			set
			{
				if ((this._kich_thuoc != value))
				{
					this.Onkich_thuocChanging(value);
					this.SendPropertyChanging();
					this._kich_thuoc = value;
					this.SendPropertyChanged("kich_thuoc");
					this.Onkich_thuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_do_day", DbType="Int")]
		public System.Nullable<int> do_day
		{
			get
			{
				return this._do_day;
			}
			set
			{
				if ((this._do_day != value))
				{
					this.Ondo_dayChanging(value);
					this.SendPropertyChanging();
					this._do_day = value;
					this.SendPropertyChanged("do_day");
					this.Ondo_dayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mau_sac", DbType="NVarChar(255)")]
		public string mau_sac
		{
			get
			{
				return this._mau_sac;
			}
			set
			{
				if ((this._mau_sac != value))
				{
					this.Onmau_sacChanging(value);
					this.SendPropertyChanging();
					this._mau_sac = value;
					this.SendPropertyChanged("mau_sac");
					this.Onmau_sacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chat_lieu", DbType="NVarChar(255)")]
		public string chat_lieu
		{
			get
			{
				return this._chat_lieu;
			}
			set
			{
				if ((this._chat_lieu != value))
				{
					this.Onchat_lieuChanging(value);
					this.SendPropertyChanging();
					this._chat_lieu = value;
					this.SendPropertyChanged("chat_lieu");
					this.Onchat_lieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gia", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> gia
		{
			get
			{
				return this._gia;
			}
			set
			{
				if ((this._gia != value))
				{
					this.OngiaChanging(value);
					this.SendPropertyChanging();
					this._gia = value;
					this.SendPropertyChanged("gia");
					this.OngiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gia_khuyen_mai", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> gia_khuyen_mai
		{
			get
			{
				return this._gia_khuyen_mai;
			}
			set
			{
				if ((this._gia_khuyen_mai != value))
				{
					this.Ongia_khuyen_maiChanging(value);
					this.SendPropertyChanging();
					this._gia_khuyen_mai = value;
					this.SendPropertyChanged("gia_khuyen_mai");
					this.Ongia_khuyen_maiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_luong_ton", DbType="Int")]
		public System.Nullable<int> so_luong_ton
		{
			get
			{
				return this._so_luong_ton;
			}
			set
			{
				if ((this._so_luong_ton != value))
				{
					this.Onso_luong_tonChanging(value);
					this.SendPropertyChanging();
					this._so_luong_ton = value;
					this.SendPropertyChanged("so_luong_ton");
					this.Onso_luong_tonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="chi_tiet_san_pham_chi_tiet_hoa_don", Storage="_chi_tiet_hoa_dons", ThisKey="chi_tiet_id", OtherKey="chi_tiet_san_pham_id")]
		public EntitySet<chi_tiet_hoa_don> chi_tiet_hoa_dons
		{
			get
			{
				return this._chi_tiet_hoa_dons;
			}
			set
			{
				this._chi_tiet_hoa_dons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="san_pham_chi_tiet_san_pham", Storage="_san_pham", ThisKey="san_pham_id", OtherKey="san_pham_id", IsForeignKey=true)]
		public san_pham san_pham
		{
			get
			{
				return this._san_pham.Entity;
			}
			set
			{
				san_pham previousValue = this._san_pham.Entity;
				if (((previousValue != value) 
							|| (this._san_pham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._san_pham.Entity = null;
						previousValue.chi_tiet_san_phams.Remove(this);
					}
					this._san_pham.Entity = value;
					if ((value != null))
					{
						value.chi_tiet_san_phams.Add(this);
						this._san_pham_id = value.san_pham_id;
					}
					else
					{
						this._san_pham_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("san_pham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_chi_tiet_hoa_dons(chi_tiet_hoa_don entity)
		{
			this.SendPropertyChanging();
			entity.chi_tiet_san_pham = this;
		}
		
		private void detach_chi_tiet_hoa_dons(chi_tiet_hoa_don entity)
		{
			this.SendPropertyChanging();
			entity.chi_tiet_san_pham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.danh_gia")]
	public partial class danh_gia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _danh_gia_id;
		
		private System.Nullable<int> _nguoi_dung_id;
		
		private System.Nullable<int> _san_pham_id;
		
		private System.Nullable<int> _so_sao;
		
		private string _binh_luan;
		
		private System.Nullable<System.DateTime> _ngay_danh_gia;
		
		private EntityRef<nguoi_dung> _nguoi_dung;
		
		private EntityRef<san_pham> _san_pham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondanh_gia_idChanging(int value);
    partial void Ondanh_gia_idChanged();
    partial void Onnguoi_dung_idChanging(System.Nullable<int> value);
    partial void Onnguoi_dung_idChanged();
    partial void Onsan_pham_idChanging(System.Nullable<int> value);
    partial void Onsan_pham_idChanged();
    partial void Onso_saoChanging(System.Nullable<int> value);
    partial void Onso_saoChanged();
    partial void Onbinh_luanChanging(string value);
    partial void Onbinh_luanChanged();
    partial void Onngay_danh_giaChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_danh_giaChanged();
    #endregion
		
		public danh_gia()
		{
			this._nguoi_dung = default(EntityRef<nguoi_dung>);
			this._san_pham = default(EntityRef<san_pham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_danh_gia_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int danh_gia_id
		{
			get
			{
				return this._danh_gia_id;
			}
			set
			{
				if ((this._danh_gia_id != value))
				{
					this.Ondanh_gia_idChanging(value);
					this.SendPropertyChanging();
					this._danh_gia_id = value;
					this.SendPropertyChanged("danh_gia_id");
					this.Ondanh_gia_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoi_dung_id", DbType="Int")]
		public System.Nullable<int> nguoi_dung_id
		{
			get
			{
				return this._nguoi_dung_id;
			}
			set
			{
				if ((this._nguoi_dung_id != value))
				{
					if (this._nguoi_dung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onnguoi_dung_idChanging(value);
					this.SendPropertyChanging();
					this._nguoi_dung_id = value;
					this.SendPropertyChanged("nguoi_dung_id");
					this.Onnguoi_dung_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_san_pham_id", DbType="Int")]
		public System.Nullable<int> san_pham_id
		{
			get
			{
				return this._san_pham_id;
			}
			set
			{
				if ((this._san_pham_id != value))
				{
					if (this._san_pham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onsan_pham_idChanging(value);
					this.SendPropertyChanging();
					this._san_pham_id = value;
					this.SendPropertyChanged("san_pham_id");
					this.Onsan_pham_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_sao", DbType="Int")]
		public System.Nullable<int> so_sao
		{
			get
			{
				return this._so_sao;
			}
			set
			{
				if ((this._so_sao != value))
				{
					this.Onso_saoChanging(value);
					this.SendPropertyChanging();
					this._so_sao = value;
					this.SendPropertyChanged("so_sao");
					this.Onso_saoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_binh_luan", DbType="NVarChar(MAX)")]
		public string binh_luan
		{
			get
			{
				return this._binh_luan;
			}
			set
			{
				if ((this._binh_luan != value))
				{
					this.Onbinh_luanChanging(value);
					this.SendPropertyChanging();
					this._binh_luan = value;
					this.SendPropertyChanged("binh_luan");
					this.Onbinh_luanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_danh_gia", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngay_danh_gia
		{
			get
			{
				return this._ngay_danh_gia;
			}
			set
			{
				if ((this._ngay_danh_gia != value))
				{
					this.Onngay_danh_giaChanging(value);
					this.SendPropertyChanging();
					this._ngay_danh_gia = value;
					this.SendPropertyChanged("ngay_danh_gia");
					this.Onngay_danh_giaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nguoi_dung_danh_gia", Storage="_nguoi_dung", ThisKey="nguoi_dung_id", OtherKey="nguoi_dung_id", IsForeignKey=true)]
		public nguoi_dung nguoi_dung
		{
			get
			{
				return this._nguoi_dung.Entity;
			}
			set
			{
				nguoi_dung previousValue = this._nguoi_dung.Entity;
				if (((previousValue != value) 
							|| (this._nguoi_dung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nguoi_dung.Entity = null;
						previousValue.danh_gias.Remove(this);
					}
					this._nguoi_dung.Entity = value;
					if ((value != null))
					{
						value.danh_gias.Add(this);
						this._nguoi_dung_id = value.nguoi_dung_id;
					}
					else
					{
						this._nguoi_dung_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("nguoi_dung");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="san_pham_danh_gia", Storage="_san_pham", ThisKey="san_pham_id", OtherKey="san_pham_id", IsForeignKey=true)]
		public san_pham san_pham
		{
			get
			{
				return this._san_pham.Entity;
			}
			set
			{
				san_pham previousValue = this._san_pham.Entity;
				if (((previousValue != value) 
							|| (this._san_pham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._san_pham.Entity = null;
						previousValue.danh_gias.Remove(this);
					}
					this._san_pham.Entity = value;
					if ((value != null))
					{
						value.danh_gias.Add(this);
						this._san_pham_id = value.san_pham_id;
					}
					else
					{
						this._san_pham_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("san_pham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.hoa_don")]
	public partial class hoa_don : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _hoa_don_id;
		
		private System.Nullable<int> _nguoi_dung_id;
		
		private System.Nullable<decimal> _tong_tien;
		
		private System.Nullable<System.DateTime> _ngay_lap;
		
		private string _trang_thai;
		
		private string _dia_chi_giao_hang;
		
		private EntitySet<log_thong_tin_hoa_don> _log_thong_tin_hoa_dons;
		
		private EntitySet<thanh_toan> _thanh_toans;
		
		private EntitySet<thong_bao> _thong_baos;
		
		private EntitySet<chi_tiet_hoa_don> _chi_tiet_hoa_dons;
		
		private EntityRef<nguoi_dung> _nguoi_dung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onhoa_don_idChanging(int value);
    partial void Onhoa_don_idChanged();
    partial void Onnguoi_dung_idChanging(System.Nullable<int> value);
    partial void Onnguoi_dung_idChanged();
    partial void Ontong_tienChanging(System.Nullable<decimal> value);
    partial void Ontong_tienChanged();
    partial void Onngay_lapChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_lapChanged();
    partial void Ontrang_thaiChanging(string value);
    partial void Ontrang_thaiChanged();
    partial void Ondia_chi_giao_hangChanging(string value);
    partial void Ondia_chi_giao_hangChanged();
    #endregion
		
		public hoa_don()
		{
			this._log_thong_tin_hoa_dons = new EntitySet<log_thong_tin_hoa_don>(new Action<log_thong_tin_hoa_don>(this.attach_log_thong_tin_hoa_dons), new Action<log_thong_tin_hoa_don>(this.detach_log_thong_tin_hoa_dons));
			this._thanh_toans = new EntitySet<thanh_toan>(new Action<thanh_toan>(this.attach_thanh_toans), new Action<thanh_toan>(this.detach_thanh_toans));
			this._thong_baos = new EntitySet<thong_bao>(new Action<thong_bao>(this.attach_thong_baos), new Action<thong_bao>(this.detach_thong_baos));
			this._chi_tiet_hoa_dons = new EntitySet<chi_tiet_hoa_don>(new Action<chi_tiet_hoa_don>(this.attach_chi_tiet_hoa_dons), new Action<chi_tiet_hoa_don>(this.detach_chi_tiet_hoa_dons));
			this._nguoi_dung = default(EntityRef<nguoi_dung>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoa_don_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int hoa_don_id
		{
			get
			{
				return this._hoa_don_id;
			}
			set
			{
				if ((this._hoa_don_id != value))
				{
					this.Onhoa_don_idChanging(value);
					this.SendPropertyChanging();
					this._hoa_don_id = value;
					this.SendPropertyChanged("hoa_don_id");
					this.Onhoa_don_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoi_dung_id", DbType="Int")]
		public System.Nullable<int> nguoi_dung_id
		{
			get
			{
				return this._nguoi_dung_id;
			}
			set
			{
				if ((this._nguoi_dung_id != value))
				{
					if (this._nguoi_dung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onnguoi_dung_idChanging(value);
					this.SendPropertyChanging();
					this._nguoi_dung_id = value;
					this.SendPropertyChanged("nguoi_dung_id");
					this.Onnguoi_dung_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tong_tien", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> tong_tien
		{
			get
			{
				return this._tong_tien;
			}
			set
			{
				if ((this._tong_tien != value))
				{
					this.Ontong_tienChanging(value);
					this.SendPropertyChanging();
					this._tong_tien = value;
					this.SendPropertyChanged("tong_tien");
					this.Ontong_tienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_lap", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngay_lap
		{
			get
			{
				return this._ngay_lap;
			}
			set
			{
				if ((this._ngay_lap != value))
				{
					this.Onngay_lapChanging(value);
					this.SendPropertyChanging();
					this._ngay_lap = value;
					this.SendPropertyChanged("ngay_lap");
					this.Onngay_lapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trang_thai", DbType="NVarChar(50)")]
		public string trang_thai
		{
			get
			{
				return this._trang_thai;
			}
			set
			{
				if ((this._trang_thai != value))
				{
					this.Ontrang_thaiChanging(value);
					this.SendPropertyChanging();
					this._trang_thai = value;
					this.SendPropertyChanged("trang_thai");
					this.Ontrang_thaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dia_chi_giao_hang", DbType="NVarChar(MAX)")]
		public string dia_chi_giao_hang
		{
			get
			{
				return this._dia_chi_giao_hang;
			}
			set
			{
				if ((this._dia_chi_giao_hang != value))
				{
					this.Ondia_chi_giao_hangChanging(value);
					this.SendPropertyChanging();
					this._dia_chi_giao_hang = value;
					this.SendPropertyChanged("dia_chi_giao_hang");
					this.Ondia_chi_giao_hangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hoa_don_log_thong_tin_hoa_don", Storage="_log_thong_tin_hoa_dons", ThisKey="hoa_don_id", OtherKey="hoa_don_id")]
		public EntitySet<log_thong_tin_hoa_don> log_thong_tin_hoa_dons
		{
			get
			{
				return this._log_thong_tin_hoa_dons;
			}
			set
			{
				this._log_thong_tin_hoa_dons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hoa_don_thanh_toan", Storage="_thanh_toans", ThisKey="hoa_don_id", OtherKey="hoa_don_id")]
		public EntitySet<thanh_toan> thanh_toans
		{
			get
			{
				return this._thanh_toans;
			}
			set
			{
				this._thanh_toans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hoa_don_thong_bao", Storage="_thong_baos", ThisKey="hoa_don_id", OtherKey="hoa_don_id")]
		public EntitySet<thong_bao> thong_baos
		{
			get
			{
				return this._thong_baos;
			}
			set
			{
				this._thong_baos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hoa_don_chi_tiet_hoa_don", Storage="_chi_tiet_hoa_dons", ThisKey="hoa_don_id", OtherKey="hoa_don_id")]
		public EntitySet<chi_tiet_hoa_don> chi_tiet_hoa_dons
		{
			get
			{
				return this._chi_tiet_hoa_dons;
			}
			set
			{
				this._chi_tiet_hoa_dons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nguoi_dung_hoa_don", Storage="_nguoi_dung", ThisKey="nguoi_dung_id", OtherKey="nguoi_dung_id", IsForeignKey=true)]
		public nguoi_dung nguoi_dung
		{
			get
			{
				return this._nguoi_dung.Entity;
			}
			set
			{
				nguoi_dung previousValue = this._nguoi_dung.Entity;
				if (((previousValue != value) 
							|| (this._nguoi_dung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nguoi_dung.Entity = null;
						previousValue.hoa_dons.Remove(this);
					}
					this._nguoi_dung.Entity = value;
					if ((value != null))
					{
						value.hoa_dons.Add(this);
						this._nguoi_dung_id = value.nguoi_dung_id;
					}
					else
					{
						this._nguoi_dung_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("nguoi_dung");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_log_thong_tin_hoa_dons(log_thong_tin_hoa_don entity)
		{
			this.SendPropertyChanging();
			entity.hoa_don = this;
		}
		
		private void detach_log_thong_tin_hoa_dons(log_thong_tin_hoa_don entity)
		{
			this.SendPropertyChanging();
			entity.hoa_don = null;
		}
		
		private void attach_thanh_toans(thanh_toan entity)
		{
			this.SendPropertyChanging();
			entity.hoa_don = this;
		}
		
		private void detach_thanh_toans(thanh_toan entity)
		{
			this.SendPropertyChanging();
			entity.hoa_don = null;
		}
		
		private void attach_thong_baos(thong_bao entity)
		{
			this.SendPropertyChanging();
			entity.hoa_don = this;
		}
		
		private void detach_thong_baos(thong_bao entity)
		{
			this.SendPropertyChanging();
			entity.hoa_don = null;
		}
		
		private void attach_chi_tiet_hoa_dons(chi_tiet_hoa_don entity)
		{
			this.SendPropertyChanging();
			entity.hoa_don = this;
		}
		
		private void detach_chi_tiet_hoa_dons(chi_tiet_hoa_don entity)
		{
			this.SendPropertyChanging();
			entity.hoa_don = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.khuyen_mai")]
	public partial class khuyen_mai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _khuyen_mai_id;
		
		private string _ten_khuyen_mai;
		
		private string _mo_ta;
		
		private System.DateTime _ngay_bat_dau;
		
		private System.DateTime _ngay_ket_thuc;
		
		private decimal _giam_gia;
		
		private System.Nullable<System.DateTime> _ngay_tao;
		
		private EntitySet<chi_tiet_khuyen_mai> _chi_tiet_khuyen_mais;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onkhuyen_mai_idChanging(int value);
    partial void Onkhuyen_mai_idChanged();
    partial void Onten_khuyen_maiChanging(string value);
    partial void Onten_khuyen_maiChanged();
    partial void Onmo_taChanging(string value);
    partial void Onmo_taChanged();
    partial void Onngay_bat_dauChanging(System.DateTime value);
    partial void Onngay_bat_dauChanged();
    partial void Onngay_ket_thucChanging(System.DateTime value);
    partial void Onngay_ket_thucChanged();
    partial void Ongiam_giaChanging(decimal value);
    partial void Ongiam_giaChanged();
    partial void Onngay_taoChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_taoChanged();
    #endregion
		
		public khuyen_mai()
		{
			this._chi_tiet_khuyen_mais = new EntitySet<chi_tiet_khuyen_mai>(new Action<chi_tiet_khuyen_mai>(this.attach_chi_tiet_khuyen_mais), new Action<chi_tiet_khuyen_mai>(this.detach_chi_tiet_khuyen_mais));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_khuyen_mai_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int khuyen_mai_id
		{
			get
			{
				return this._khuyen_mai_id;
			}
			set
			{
				if ((this._khuyen_mai_id != value))
				{
					this.Onkhuyen_mai_idChanging(value);
					this.SendPropertyChanging();
					this._khuyen_mai_id = value;
					this.SendPropertyChanged("khuyen_mai_id");
					this.Onkhuyen_mai_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_khuyen_mai", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string ten_khuyen_mai
		{
			get
			{
				return this._ten_khuyen_mai;
			}
			set
			{
				if ((this._ten_khuyen_mai != value))
				{
					this.Onten_khuyen_maiChanging(value);
					this.SendPropertyChanging();
					this._ten_khuyen_mai = value;
					this.SendPropertyChanged("ten_khuyen_mai");
					this.Onten_khuyen_maiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mo_ta", DbType="NVarChar(MAX)")]
		public string mo_ta
		{
			get
			{
				return this._mo_ta;
			}
			set
			{
				if ((this._mo_ta != value))
				{
					this.Onmo_taChanging(value);
					this.SendPropertyChanging();
					this._mo_ta = value;
					this.SendPropertyChanged("mo_ta");
					this.Onmo_taChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_bat_dau", DbType="DateTime NOT NULL")]
		public System.DateTime ngay_bat_dau
		{
			get
			{
				return this._ngay_bat_dau;
			}
			set
			{
				if ((this._ngay_bat_dau != value))
				{
					this.Onngay_bat_dauChanging(value);
					this.SendPropertyChanging();
					this._ngay_bat_dau = value;
					this.SendPropertyChanged("ngay_bat_dau");
					this.Onngay_bat_dauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_ket_thuc", DbType="DateTime NOT NULL")]
		public System.DateTime ngay_ket_thuc
		{
			get
			{
				return this._ngay_ket_thuc;
			}
			set
			{
				if ((this._ngay_ket_thuc != value))
				{
					this.Onngay_ket_thucChanging(value);
					this.SendPropertyChanging();
					this._ngay_ket_thuc = value;
					this.SendPropertyChanged("ngay_ket_thuc");
					this.Onngay_ket_thucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giam_gia", DbType="Decimal(10,2) NOT NULL")]
		public decimal giam_gia
		{
			get
			{
				return this._giam_gia;
			}
			set
			{
				if ((this._giam_gia != value))
				{
					this.Ongiam_giaChanging(value);
					this.SendPropertyChanging();
					this._giam_gia = value;
					this.SendPropertyChanged("giam_gia");
					this.Ongiam_giaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_tao", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngay_tao
		{
			get
			{
				return this._ngay_tao;
			}
			set
			{
				if ((this._ngay_tao != value))
				{
					this.Onngay_taoChanging(value);
					this.SendPropertyChanging();
					this._ngay_tao = value;
					this.SendPropertyChanged("ngay_tao");
					this.Onngay_taoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khuyen_mai_chi_tiet_khuyen_mai", Storage="_chi_tiet_khuyen_mais", ThisKey="khuyen_mai_id", OtherKey="khuyen_mai_id")]
		public EntitySet<chi_tiet_khuyen_mai> chi_tiet_khuyen_mais
		{
			get
			{
				return this._chi_tiet_khuyen_mais;
			}
			set
			{
				this._chi_tiet_khuyen_mais.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_chi_tiet_khuyen_mais(chi_tiet_khuyen_mai entity)
		{
			this.SendPropertyChanging();
			entity.khuyen_mai = this;
		}
		
		private void detach_chi_tiet_khuyen_mais(chi_tiet_khuyen_mai entity)
		{
			this.SendPropertyChanging();
			entity.khuyen_mai = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.log_thong_tin_hoa_don")]
	public partial class log_thong_tin_hoa_don : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _log_id;
		
		private System.Nullable<int> _hoa_don_id;
		
		private System.Nullable<System.DateTime> _ngay_gio_thay_doi;
		
		private string _trang_thai_moi;
		
		private EntityRef<hoa_don> _hoa_don;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onlog_idChanging(int value);
    partial void Onlog_idChanged();
    partial void Onhoa_don_idChanging(System.Nullable<int> value);
    partial void Onhoa_don_idChanged();
    partial void Onngay_gio_thay_doiChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_gio_thay_doiChanged();
    partial void Ontrang_thai_moiChanging(string value);
    partial void Ontrang_thai_moiChanged();
    #endregion
		
		public log_thong_tin_hoa_don()
		{
			this._hoa_don = default(EntityRef<hoa_don>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_log_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int log_id
		{
			get
			{
				return this._log_id;
			}
			set
			{
				if ((this._log_id != value))
				{
					this.Onlog_idChanging(value);
					this.SendPropertyChanging();
					this._log_id = value;
					this.SendPropertyChanged("log_id");
					this.Onlog_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoa_don_id", DbType="Int")]
		public System.Nullable<int> hoa_don_id
		{
			get
			{
				return this._hoa_don_id;
			}
			set
			{
				if ((this._hoa_don_id != value))
				{
					if (this._hoa_don.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onhoa_don_idChanging(value);
					this.SendPropertyChanging();
					this._hoa_don_id = value;
					this.SendPropertyChanged("hoa_don_id");
					this.Onhoa_don_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_gio_thay_doi", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngay_gio_thay_doi
		{
			get
			{
				return this._ngay_gio_thay_doi;
			}
			set
			{
				if ((this._ngay_gio_thay_doi != value))
				{
					this.Onngay_gio_thay_doiChanging(value);
					this.SendPropertyChanging();
					this._ngay_gio_thay_doi = value;
					this.SendPropertyChanged("ngay_gio_thay_doi");
					this.Onngay_gio_thay_doiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trang_thai_moi", DbType="NVarChar(50)")]
		public string trang_thai_moi
		{
			get
			{
				return this._trang_thai_moi;
			}
			set
			{
				if ((this._trang_thai_moi != value))
				{
					this.Ontrang_thai_moiChanging(value);
					this.SendPropertyChanging();
					this._trang_thai_moi = value;
					this.SendPropertyChanged("trang_thai_moi");
					this.Ontrang_thai_moiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hoa_don_log_thong_tin_hoa_don", Storage="_hoa_don", ThisKey="hoa_don_id", OtherKey="hoa_don_id", IsForeignKey=true)]
		public hoa_don hoa_don
		{
			get
			{
				return this._hoa_don.Entity;
			}
			set
			{
				hoa_don previousValue = this._hoa_don.Entity;
				if (((previousValue != value) 
							|| (this._hoa_don.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._hoa_don.Entity = null;
						previousValue.log_thong_tin_hoa_dons.Remove(this);
					}
					this._hoa_don.Entity = value;
					if ((value != null))
					{
						value.log_thong_tin_hoa_dons.Add(this);
						this._hoa_don_id = value.hoa_don_id;
					}
					else
					{
						this._hoa_don_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("hoa_don");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nguoi_dung")]
	public partial class nguoi_dung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _nguoi_dung_id;
		
		private string _ten_dang_nhap;
		
		private string _mat_khau_hash;
		
		private string _email;
		
		private string _so_dien_thoai;
		
		private string _dia_chi;
		
		private string _vai_tro;
		
		private System.Nullable<System.DateTime> _ngay_tao;
		
		private EntitySet<danh_gia> _danh_gias;
		
		private EntitySet<hoa_don> _hoa_dons;
		
		private EntitySet<thong_bao> _thong_baos;
		
		private EntitySet<thong_bao_nguoi_dung> _thong_bao_nguoi_dungs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onnguoi_dung_idChanging(int value);
    partial void Onnguoi_dung_idChanged();
    partial void Onten_dang_nhapChanging(string value);
    partial void Onten_dang_nhapChanged();
    partial void Onmat_khau_hashChanging(string value);
    partial void Onmat_khau_hashChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Onso_dien_thoaiChanging(string value);
    partial void Onso_dien_thoaiChanged();
    partial void Ondia_chiChanging(string value);
    partial void Ondia_chiChanged();
    partial void Onvai_troChanging(string value);
    partial void Onvai_troChanged();
    partial void Onngay_taoChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_taoChanged();
    #endregion
		
		public nguoi_dung()
		{
			this._danh_gias = new EntitySet<danh_gia>(new Action<danh_gia>(this.attach_danh_gias), new Action<danh_gia>(this.detach_danh_gias));
			this._hoa_dons = new EntitySet<hoa_don>(new Action<hoa_don>(this.attach_hoa_dons), new Action<hoa_don>(this.detach_hoa_dons));
			this._thong_baos = new EntitySet<thong_bao>(new Action<thong_bao>(this.attach_thong_baos), new Action<thong_bao>(this.detach_thong_baos));
			this._thong_bao_nguoi_dungs = new EntitySet<thong_bao_nguoi_dung>(new Action<thong_bao_nguoi_dung>(this.attach_thong_bao_nguoi_dungs), new Action<thong_bao_nguoi_dung>(this.detach_thong_bao_nguoi_dungs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoi_dung_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int nguoi_dung_id
		{
			get
			{
				return this._nguoi_dung_id;
			}
			set
			{
				if ((this._nguoi_dung_id != value))
				{
					this.Onnguoi_dung_idChanging(value);
					this.SendPropertyChanging();
					this._nguoi_dung_id = value;
					this.SendPropertyChanged("nguoi_dung_id");
					this.Onnguoi_dung_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_dang_nhap", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string ten_dang_nhap
		{
			get
			{
				return this._ten_dang_nhap;
			}
			set
			{
				if ((this._ten_dang_nhap != value))
				{
					this.Onten_dang_nhapChanging(value);
					this.SendPropertyChanging();
					this._ten_dang_nhap = value;
					this.SendPropertyChanged("ten_dang_nhap");
					this.Onten_dang_nhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mat_khau_hash", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string mat_khau_hash
		{
			get
			{
				return this._mat_khau_hash;
			}
			set
			{
				if ((this._mat_khau_hash != value))
				{
					this.Onmat_khau_hashChanging(value);
					this.SendPropertyChanging();
					this._mat_khau_hash = value;
					this.SendPropertyChanged("mat_khau_hash");
					this.Onmat_khau_hashChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_dien_thoai", DbType="NVarChar(20)")]
		public string so_dien_thoai
		{
			get
			{
				return this._so_dien_thoai;
			}
			set
			{
				if ((this._so_dien_thoai != value))
				{
					this.Onso_dien_thoaiChanging(value);
					this.SendPropertyChanging();
					this._so_dien_thoai = value;
					this.SendPropertyChanged("so_dien_thoai");
					this.Onso_dien_thoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dia_chi", DbType="NVarChar(MAX)")]
		public string dia_chi
		{
			get
			{
				return this._dia_chi;
			}
			set
			{
				if ((this._dia_chi != value))
				{
					this.Ondia_chiChanging(value);
					this.SendPropertyChanging();
					this._dia_chi = value;
					this.SendPropertyChanged("dia_chi");
					this.Ondia_chiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vai_tro", DbType="NVarChar(50)")]
		public string vai_tro
		{
			get
			{
				return this._vai_tro;
			}
			set
			{
				if ((this._vai_tro != value))
				{
					this.Onvai_troChanging(value);
					this.SendPropertyChanging();
					this._vai_tro = value;
					this.SendPropertyChanged("vai_tro");
					this.Onvai_troChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_tao", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngay_tao
		{
			get
			{
				return this._ngay_tao;
			}
			set
			{
				if ((this._ngay_tao != value))
				{
					this.Onngay_taoChanging(value);
					this.SendPropertyChanging();
					this._ngay_tao = value;
					this.SendPropertyChanged("ngay_tao");
					this.Onngay_taoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nguoi_dung_danh_gia", Storage="_danh_gias", ThisKey="nguoi_dung_id", OtherKey="nguoi_dung_id")]
		public EntitySet<danh_gia> danh_gias
		{
			get
			{
				return this._danh_gias;
			}
			set
			{
				this._danh_gias.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nguoi_dung_hoa_don", Storage="_hoa_dons", ThisKey="nguoi_dung_id", OtherKey="nguoi_dung_id")]
		public EntitySet<hoa_don> hoa_dons
		{
			get
			{
				return this._hoa_dons;
			}
			set
			{
				this._hoa_dons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nguoi_dung_thong_bao", Storage="_thong_baos", ThisKey="nguoi_dung_id", OtherKey="nguoi_dung_id")]
		public EntitySet<thong_bao> thong_baos
		{
			get
			{
				return this._thong_baos;
			}
			set
			{
				this._thong_baos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nguoi_dung_thong_bao_nguoi_dung", Storage="_thong_bao_nguoi_dungs", ThisKey="nguoi_dung_id", OtherKey="nguoi_dung_id")]
		public EntitySet<thong_bao_nguoi_dung> thong_bao_nguoi_dungs
		{
			get
			{
				return this._thong_bao_nguoi_dungs;
			}
			set
			{
				this._thong_bao_nguoi_dungs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_danh_gias(danh_gia entity)
		{
			this.SendPropertyChanging();
			entity.nguoi_dung = this;
		}
		
		private void detach_danh_gias(danh_gia entity)
		{
			this.SendPropertyChanging();
			entity.nguoi_dung = null;
		}
		
		private void attach_hoa_dons(hoa_don entity)
		{
			this.SendPropertyChanging();
			entity.nguoi_dung = this;
		}
		
		private void detach_hoa_dons(hoa_don entity)
		{
			this.SendPropertyChanging();
			entity.nguoi_dung = null;
		}
		
		private void attach_thong_baos(thong_bao entity)
		{
			this.SendPropertyChanging();
			entity.nguoi_dung = this;
		}
		
		private void detach_thong_baos(thong_bao entity)
		{
			this.SendPropertyChanging();
			entity.nguoi_dung = null;
		}
		
		private void attach_thong_bao_nguoi_dungs(thong_bao_nguoi_dung entity)
		{
			this.SendPropertyChanging();
			entity.nguoi_dung = this;
		}
		
		private void detach_thong_bao_nguoi_dungs(thong_bao_nguoi_dung entity)
		{
			this.SendPropertyChanging();
			entity.nguoi_dung = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.san_pham")]
	public partial class san_pham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _san_pham_id;
		
		private string _ten_san_pham;
		
		private string _loai_san_pham;
		
		private string _mo_ta_chung;
		
		private string _thuong_hieu;
		
		private System.Nullable<decimal> _giam_gia;
		
		private string _hinh_anh_chinh;
		
		private string _danh_sach_hinh_anh;
		
		private EntitySet<chi_tiet_khuyen_mai> _chi_tiet_khuyen_mais;
		
		private EntitySet<chi_tiet_san_pham> _chi_tiet_san_phams;
		
		private EntitySet<danh_gia> _danh_gias;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsan_pham_idChanging(int value);
    partial void Onsan_pham_idChanged();
    partial void Onten_san_phamChanging(string value);
    partial void Onten_san_phamChanged();
    partial void Onloai_san_phamChanging(string value);
    partial void Onloai_san_phamChanged();
    partial void Onmo_ta_chungChanging(string value);
    partial void Onmo_ta_chungChanged();
    partial void Onthuong_hieuChanging(string value);
    partial void Onthuong_hieuChanged();
    partial void Ongiam_giaChanging(System.Nullable<decimal> value);
    partial void Ongiam_giaChanged();
    partial void Onhinh_anh_chinhChanging(string value);
    partial void Onhinh_anh_chinhChanged();
    partial void Ondanh_sach_hinh_anhChanging(string value);
    partial void Ondanh_sach_hinh_anhChanged();
    #endregion
		
		public san_pham()
		{
			this._chi_tiet_khuyen_mais = new EntitySet<chi_tiet_khuyen_mai>(new Action<chi_tiet_khuyen_mai>(this.attach_chi_tiet_khuyen_mais), new Action<chi_tiet_khuyen_mai>(this.detach_chi_tiet_khuyen_mais));
			this._chi_tiet_san_phams = new EntitySet<chi_tiet_san_pham>(new Action<chi_tiet_san_pham>(this.attach_chi_tiet_san_phams), new Action<chi_tiet_san_pham>(this.detach_chi_tiet_san_phams));
			this._danh_gias = new EntitySet<danh_gia>(new Action<danh_gia>(this.attach_danh_gias), new Action<danh_gia>(this.detach_danh_gias));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_san_pham_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int san_pham_id
		{
			get
			{
				return this._san_pham_id;
			}
			set
			{
				if ((this._san_pham_id != value))
				{
					this.Onsan_pham_idChanging(value);
					this.SendPropertyChanging();
					this._san_pham_id = value;
					this.SendPropertyChanged("san_pham_id");
					this.Onsan_pham_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_san_pham", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string ten_san_pham
		{
			get
			{
				return this._ten_san_pham;
			}
			set
			{
				if ((this._ten_san_pham != value))
				{
					this.Onten_san_phamChanging(value);
					this.SendPropertyChanging();
					this._ten_san_pham = value;
					this.SendPropertyChanged("ten_san_pham");
					this.Onten_san_phamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loai_san_pham", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string loai_san_pham
		{
			get
			{
				return this._loai_san_pham;
			}
			set
			{
				if ((this._loai_san_pham != value))
				{
					this.Onloai_san_phamChanging(value);
					this.SendPropertyChanging();
					this._loai_san_pham = value;
					this.SendPropertyChanged("loai_san_pham");
					this.Onloai_san_phamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mo_ta_chung", DbType="NVarChar(MAX)")]
		public string mo_ta_chung
		{
			get
			{
				return this._mo_ta_chung;
			}
			set
			{
				if ((this._mo_ta_chung != value))
				{
					this.Onmo_ta_chungChanging(value);
					this.SendPropertyChanging();
					this._mo_ta_chung = value;
					this.SendPropertyChanged("mo_ta_chung");
					this.Onmo_ta_chungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thuong_hieu", DbType="NVarChar(255)")]
		public string thuong_hieu
		{
			get
			{
				return this._thuong_hieu;
			}
			set
			{
				if ((this._thuong_hieu != value))
				{
					this.Onthuong_hieuChanging(value);
					this.SendPropertyChanging();
					this._thuong_hieu = value;
					this.SendPropertyChanged("thuong_hieu");
					this.Onthuong_hieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giam_gia", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> giam_gia
		{
			get
			{
				return this._giam_gia;
			}
			set
			{
				if ((this._giam_gia != value))
				{
					this.Ongiam_giaChanging(value);
					this.SendPropertyChanging();
					this._giam_gia = value;
					this.SendPropertyChanged("giam_gia");
					this.Ongiam_giaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hinh_anh_chinh", DbType="NVarChar(255)")]
		public string hinh_anh_chinh
		{
			get
			{
				return this._hinh_anh_chinh;
			}
			set
			{
				if ((this._hinh_anh_chinh != value))
				{
					this.Onhinh_anh_chinhChanging(value);
					this.SendPropertyChanging();
					this._hinh_anh_chinh = value;
					this.SendPropertyChanged("hinh_anh_chinh");
					this.Onhinh_anh_chinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_danh_sach_hinh_anh", DbType="NVarChar(MAX)")]
		public string danh_sach_hinh_anh
		{
			get
			{
				return this._danh_sach_hinh_anh;
			}
			set
			{
				if ((this._danh_sach_hinh_anh != value))
				{
					this.Ondanh_sach_hinh_anhChanging(value);
					this.SendPropertyChanging();
					this._danh_sach_hinh_anh = value;
					this.SendPropertyChanged("danh_sach_hinh_anh");
					this.Ondanh_sach_hinh_anhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="san_pham_chi_tiet_khuyen_mai", Storage="_chi_tiet_khuyen_mais", ThisKey="san_pham_id", OtherKey="san_pham_id")]
		public EntitySet<chi_tiet_khuyen_mai> chi_tiet_khuyen_mais
		{
			get
			{
				return this._chi_tiet_khuyen_mais;
			}
			set
			{
				this._chi_tiet_khuyen_mais.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="san_pham_chi_tiet_san_pham", Storage="_chi_tiet_san_phams", ThisKey="san_pham_id", OtherKey="san_pham_id")]
		public EntitySet<chi_tiet_san_pham> chi_tiet_san_phams
		{
			get
			{
				return this._chi_tiet_san_phams;
			}
			set
			{
				this._chi_tiet_san_phams.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="san_pham_danh_gia", Storage="_danh_gias", ThisKey="san_pham_id", OtherKey="san_pham_id")]
		public EntitySet<danh_gia> danh_gias
		{
			get
			{
				return this._danh_gias;
			}
			set
			{
				this._danh_gias.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_chi_tiet_khuyen_mais(chi_tiet_khuyen_mai entity)
		{
			this.SendPropertyChanging();
			entity.san_pham = this;
		}
		
		private void detach_chi_tiet_khuyen_mais(chi_tiet_khuyen_mai entity)
		{
			this.SendPropertyChanging();
			entity.san_pham = null;
		}
		
		private void attach_chi_tiet_san_phams(chi_tiet_san_pham entity)
		{
			this.SendPropertyChanging();
			entity.san_pham = this;
		}
		
		private void detach_chi_tiet_san_phams(chi_tiet_san_pham entity)
		{
			this.SendPropertyChanging();
			entity.san_pham = null;
		}
		
		private void attach_danh_gias(danh_gia entity)
		{
			this.SendPropertyChanging();
			entity.san_pham = this;
		}
		
		private void detach_danh_gias(danh_gia entity)
		{
			this.SendPropertyChanging();
			entity.san_pham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.thanh_toan")]
	public partial class thanh_toan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _thanh_toan_id;
		
		private System.Nullable<int> _hoa_don_id;
		
		private string _phuong_thuc_thanh_toan;
		
		private string _trang_thai;
		
		private System.Nullable<System.DateTime> _ngay_thanh_toan;
		
		private EntityRef<hoa_don> _hoa_don;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onthanh_toan_idChanging(int value);
    partial void Onthanh_toan_idChanged();
    partial void Onhoa_don_idChanging(System.Nullable<int> value);
    partial void Onhoa_don_idChanged();
    partial void Onphuong_thuc_thanh_toanChanging(string value);
    partial void Onphuong_thuc_thanh_toanChanged();
    partial void Ontrang_thaiChanging(string value);
    partial void Ontrang_thaiChanged();
    partial void Onngay_thanh_toanChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_thanh_toanChanged();
    #endregion
		
		public thanh_toan()
		{
			this._hoa_don = default(EntityRef<hoa_don>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thanh_toan_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int thanh_toan_id
		{
			get
			{
				return this._thanh_toan_id;
			}
			set
			{
				if ((this._thanh_toan_id != value))
				{
					this.Onthanh_toan_idChanging(value);
					this.SendPropertyChanging();
					this._thanh_toan_id = value;
					this.SendPropertyChanged("thanh_toan_id");
					this.Onthanh_toan_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoa_don_id", DbType="Int")]
		public System.Nullable<int> hoa_don_id
		{
			get
			{
				return this._hoa_don_id;
			}
			set
			{
				if ((this._hoa_don_id != value))
				{
					if (this._hoa_don.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onhoa_don_idChanging(value);
					this.SendPropertyChanging();
					this._hoa_don_id = value;
					this.SendPropertyChanged("hoa_don_id");
					this.Onhoa_don_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phuong_thuc_thanh_toan", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string phuong_thuc_thanh_toan
		{
			get
			{
				return this._phuong_thuc_thanh_toan;
			}
			set
			{
				if ((this._phuong_thuc_thanh_toan != value))
				{
					this.Onphuong_thuc_thanh_toanChanging(value);
					this.SendPropertyChanging();
					this._phuong_thuc_thanh_toan = value;
					this.SendPropertyChanged("phuong_thuc_thanh_toan");
					this.Onphuong_thuc_thanh_toanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trang_thai", DbType="NVarChar(50)")]
		public string trang_thai
		{
			get
			{
				return this._trang_thai;
			}
			set
			{
				if ((this._trang_thai != value))
				{
					this.Ontrang_thaiChanging(value);
					this.SendPropertyChanging();
					this._trang_thai = value;
					this.SendPropertyChanged("trang_thai");
					this.Ontrang_thaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_thanh_toan", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngay_thanh_toan
		{
			get
			{
				return this._ngay_thanh_toan;
			}
			set
			{
				if ((this._ngay_thanh_toan != value))
				{
					this.Onngay_thanh_toanChanging(value);
					this.SendPropertyChanging();
					this._ngay_thanh_toan = value;
					this.SendPropertyChanged("ngay_thanh_toan");
					this.Onngay_thanh_toanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hoa_don_thanh_toan", Storage="_hoa_don", ThisKey="hoa_don_id", OtherKey="hoa_don_id", IsForeignKey=true)]
		public hoa_don hoa_don
		{
			get
			{
				return this._hoa_don.Entity;
			}
			set
			{
				hoa_don previousValue = this._hoa_don.Entity;
				if (((previousValue != value) 
							|| (this._hoa_don.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._hoa_don.Entity = null;
						previousValue.thanh_toans.Remove(this);
					}
					this._hoa_don.Entity = value;
					if ((value != null))
					{
						value.thanh_toans.Add(this);
						this._hoa_don_id = value.hoa_don_id;
					}
					else
					{
						this._hoa_don_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("hoa_don");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.thong_bao")]
	public partial class thong_bao : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _thong_bao_id;
		
		private System.Nullable<int> _hoa_don_id;
		
		private System.Nullable<int> _nguoi_dung_id;
		
		private string _thong_bao1;
		
		private System.Nullable<System.DateTime> _ngay_tao;
		
		private System.Nullable<bool> _da_xem;
		
		private EntityRef<hoa_don> _hoa_don;
		
		private EntityRef<nguoi_dung> _nguoi_dung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onthong_bao_idChanging(int value);
    partial void Onthong_bao_idChanged();
    partial void Onhoa_don_idChanging(System.Nullable<int> value);
    partial void Onhoa_don_idChanged();
    partial void Onnguoi_dung_idChanging(System.Nullable<int> value);
    partial void Onnguoi_dung_idChanged();
    partial void Onthong_bao1Changing(string value);
    partial void Onthong_bao1Changed();
    partial void Onngay_taoChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_taoChanged();
    partial void Onda_xemChanging(System.Nullable<bool> value);
    partial void Onda_xemChanged();
    #endregion
		
		public thong_bao()
		{
			this._hoa_don = default(EntityRef<hoa_don>);
			this._nguoi_dung = default(EntityRef<nguoi_dung>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thong_bao_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int thong_bao_id
		{
			get
			{
				return this._thong_bao_id;
			}
			set
			{
				if ((this._thong_bao_id != value))
				{
					this.Onthong_bao_idChanging(value);
					this.SendPropertyChanging();
					this._thong_bao_id = value;
					this.SendPropertyChanged("thong_bao_id");
					this.Onthong_bao_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoa_don_id", DbType="Int")]
		public System.Nullable<int> hoa_don_id
		{
			get
			{
				return this._hoa_don_id;
			}
			set
			{
				if ((this._hoa_don_id != value))
				{
					if (this._hoa_don.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onhoa_don_idChanging(value);
					this.SendPropertyChanging();
					this._hoa_don_id = value;
					this.SendPropertyChanged("hoa_don_id");
					this.Onhoa_don_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoi_dung_id", DbType="Int")]
		public System.Nullable<int> nguoi_dung_id
		{
			get
			{
				return this._nguoi_dung_id;
			}
			set
			{
				if ((this._nguoi_dung_id != value))
				{
					if (this._nguoi_dung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onnguoi_dung_idChanging(value);
					this.SendPropertyChanging();
					this._nguoi_dung_id = value;
					this.SendPropertyChanged("nguoi_dung_id");
					this.Onnguoi_dung_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="thong_bao", Storage="_thong_bao1", DbType="NVarChar(MAX)")]
		public string thong_bao1
		{
			get
			{
				return this._thong_bao1;
			}
			set
			{
				if ((this._thong_bao1 != value))
				{
					this.Onthong_bao1Changing(value);
					this.SendPropertyChanging();
					this._thong_bao1 = value;
					this.SendPropertyChanged("thong_bao1");
					this.Onthong_bao1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_tao", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngay_tao
		{
			get
			{
				return this._ngay_tao;
			}
			set
			{
				if ((this._ngay_tao != value))
				{
					this.Onngay_taoChanging(value);
					this.SendPropertyChanging();
					this._ngay_tao = value;
					this.SendPropertyChanged("ngay_tao");
					this.Onngay_taoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_da_xem", DbType="Bit")]
		public System.Nullable<bool> da_xem
		{
			get
			{
				return this._da_xem;
			}
			set
			{
				if ((this._da_xem != value))
				{
					this.Onda_xemChanging(value);
					this.SendPropertyChanging();
					this._da_xem = value;
					this.SendPropertyChanged("da_xem");
					this.Onda_xemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hoa_don_thong_bao", Storage="_hoa_don", ThisKey="hoa_don_id", OtherKey="hoa_don_id", IsForeignKey=true)]
		public hoa_don hoa_don
		{
			get
			{
				return this._hoa_don.Entity;
			}
			set
			{
				hoa_don previousValue = this._hoa_don.Entity;
				if (((previousValue != value) 
							|| (this._hoa_don.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._hoa_don.Entity = null;
						previousValue.thong_baos.Remove(this);
					}
					this._hoa_don.Entity = value;
					if ((value != null))
					{
						value.thong_baos.Add(this);
						this._hoa_don_id = value.hoa_don_id;
					}
					else
					{
						this._hoa_don_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("hoa_don");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nguoi_dung_thong_bao", Storage="_nguoi_dung", ThisKey="nguoi_dung_id", OtherKey="nguoi_dung_id", IsForeignKey=true)]
		public nguoi_dung nguoi_dung
		{
			get
			{
				return this._nguoi_dung.Entity;
			}
			set
			{
				nguoi_dung previousValue = this._nguoi_dung.Entity;
				if (((previousValue != value) 
							|| (this._nguoi_dung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nguoi_dung.Entity = null;
						previousValue.thong_baos.Remove(this);
					}
					this._nguoi_dung.Entity = value;
					if ((value != null))
					{
						value.thong_baos.Add(this);
						this._nguoi_dung_id = value.nguoi_dung_id;
					}
					else
					{
						this._nguoi_dung_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("nguoi_dung");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.thong_bao_nguoi_dung")]
	public partial class thong_bao_nguoi_dung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _thong_bao_id;
		
		private System.Nullable<int> _nguoi_dung_id;
		
		private string _thong_bao;
		
		private System.Nullable<System.DateTime> _ngay_tao;
		
		private System.Nullable<bool> _da_xem;
		
		private EntityRef<nguoi_dung> _nguoi_dung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onthong_bao_idChanging(int value);
    partial void Onthong_bao_idChanged();
    partial void Onnguoi_dung_idChanging(System.Nullable<int> value);
    partial void Onnguoi_dung_idChanged();
    partial void Onthong_baoChanging(string value);
    partial void Onthong_baoChanged();
    partial void Onngay_taoChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_taoChanged();
    partial void Onda_xemChanging(System.Nullable<bool> value);
    partial void Onda_xemChanged();
    #endregion
		
		public thong_bao_nguoi_dung()
		{
			this._nguoi_dung = default(EntityRef<nguoi_dung>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thong_bao_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int thong_bao_id
		{
			get
			{
				return this._thong_bao_id;
			}
			set
			{
				if ((this._thong_bao_id != value))
				{
					this.Onthong_bao_idChanging(value);
					this.SendPropertyChanging();
					this._thong_bao_id = value;
					this.SendPropertyChanged("thong_bao_id");
					this.Onthong_bao_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoi_dung_id", DbType="Int")]
		public System.Nullable<int> nguoi_dung_id
		{
			get
			{
				return this._nguoi_dung_id;
			}
			set
			{
				if ((this._nguoi_dung_id != value))
				{
					if (this._nguoi_dung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onnguoi_dung_idChanging(value);
					this.SendPropertyChanging();
					this._nguoi_dung_id = value;
					this.SendPropertyChanged("nguoi_dung_id");
					this.Onnguoi_dung_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thong_bao", DbType="NVarChar(MAX)")]
		public string thong_bao
		{
			get
			{
				return this._thong_bao;
			}
			set
			{
				if ((this._thong_bao != value))
				{
					this.Onthong_baoChanging(value);
					this.SendPropertyChanging();
					this._thong_bao = value;
					this.SendPropertyChanged("thong_bao");
					this.Onthong_baoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_tao", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngay_tao
		{
			get
			{
				return this._ngay_tao;
			}
			set
			{
				if ((this._ngay_tao != value))
				{
					this.Onngay_taoChanging(value);
					this.SendPropertyChanging();
					this._ngay_tao = value;
					this.SendPropertyChanged("ngay_tao");
					this.Onngay_taoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_da_xem", DbType="Bit")]
		public System.Nullable<bool> da_xem
		{
			get
			{
				return this._da_xem;
			}
			set
			{
				if ((this._da_xem != value))
				{
					this.Onda_xemChanging(value);
					this.SendPropertyChanging();
					this._da_xem = value;
					this.SendPropertyChanged("da_xem");
					this.Onda_xemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nguoi_dung_thong_bao_nguoi_dung", Storage="_nguoi_dung", ThisKey="nguoi_dung_id", OtherKey="nguoi_dung_id", IsForeignKey=true)]
		public nguoi_dung nguoi_dung
		{
			get
			{
				return this._nguoi_dung.Entity;
			}
			set
			{
				nguoi_dung previousValue = this._nguoi_dung.Entity;
				if (((previousValue != value) 
							|| (this._nguoi_dung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nguoi_dung.Entity = null;
						previousValue.thong_bao_nguoi_dungs.Remove(this);
					}
					this._nguoi_dung.Entity = value;
					if ((value != null))
					{
						value.thong_bao_nguoi_dungs.Add(this);
						this._nguoi_dung_id = value.nguoi_dung_id;
					}
					else
					{
						this._nguoi_dung_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("nguoi_dung");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.chi_tiet_hoa_don")]
	public partial class chi_tiet_hoa_don : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _chi_tiet_id;
		
		private System.Nullable<int> _hoa_don_id;
		
		private System.Nullable<int> _chi_tiet_san_pham_id;
		
		private string _kich_thuoc;
		
		private System.Nullable<int> _so_luong;
		
		private System.Nullable<decimal> _gia;
		
		private System.Nullable<decimal> _tong_tien;
		
		private System.Nullable<int> _do_day;
		
		private string _mau_sac;
		
		private EntityRef<chi_tiet_san_pham> _chi_tiet_san_pham;
		
		private EntityRef<hoa_don> _hoa_don;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onchi_tiet_idChanging(int value);
    partial void Onchi_tiet_idChanged();
    partial void Onhoa_don_idChanging(System.Nullable<int> value);
    partial void Onhoa_don_idChanged();
    partial void Onchi_tiet_san_pham_idChanging(System.Nullable<int> value);
    partial void Onchi_tiet_san_pham_idChanged();
    partial void Onkich_thuocChanging(string value);
    partial void Onkich_thuocChanged();
    partial void Onso_luongChanging(System.Nullable<int> value);
    partial void Onso_luongChanged();
    partial void OngiaChanging(System.Nullable<decimal> value);
    partial void OngiaChanged();
    partial void Ontong_tienChanging(System.Nullable<decimal> value);
    partial void Ontong_tienChanged();
    partial void Ondo_dayChanging(System.Nullable<int> value);
    partial void Ondo_dayChanged();
    partial void Onmau_sacChanging(string value);
    partial void Onmau_sacChanged();
    #endregion
		
		public chi_tiet_hoa_don()
		{
			this._chi_tiet_san_pham = default(EntityRef<chi_tiet_san_pham>);
			this._hoa_don = default(EntityRef<hoa_don>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chi_tiet_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int chi_tiet_id
		{
			get
			{
				return this._chi_tiet_id;
			}
			set
			{
				if ((this._chi_tiet_id != value))
				{
					this.Onchi_tiet_idChanging(value);
					this.SendPropertyChanging();
					this._chi_tiet_id = value;
					this.SendPropertyChanged("chi_tiet_id");
					this.Onchi_tiet_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoa_don_id", DbType="Int")]
		public System.Nullable<int> hoa_don_id
		{
			get
			{
				return this._hoa_don_id;
			}
			set
			{
				if ((this._hoa_don_id != value))
				{
					if (this._hoa_don.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onhoa_don_idChanging(value);
					this.SendPropertyChanging();
					this._hoa_don_id = value;
					this.SendPropertyChanged("hoa_don_id");
					this.Onhoa_don_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chi_tiet_san_pham_id", DbType="Int")]
		public System.Nullable<int> chi_tiet_san_pham_id
		{
			get
			{
				return this._chi_tiet_san_pham_id;
			}
			set
			{
				if ((this._chi_tiet_san_pham_id != value))
				{
					if (this._chi_tiet_san_pham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onchi_tiet_san_pham_idChanging(value);
					this.SendPropertyChanging();
					this._chi_tiet_san_pham_id = value;
					this.SendPropertyChanged("chi_tiet_san_pham_id");
					this.Onchi_tiet_san_pham_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kich_thuoc", DbType="NVarChar(255)")]
		public string kich_thuoc
		{
			get
			{
				return this._kich_thuoc;
			}
			set
			{
				if ((this._kich_thuoc != value))
				{
					this.Onkich_thuocChanging(value);
					this.SendPropertyChanging();
					this._kich_thuoc = value;
					this.SendPropertyChanged("kich_thuoc");
					this.Onkich_thuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_luong", DbType="Int")]
		public System.Nullable<int> so_luong
		{
			get
			{
				return this._so_luong;
			}
			set
			{
				if ((this._so_luong != value))
				{
					this.Onso_luongChanging(value);
					this.SendPropertyChanging();
					this._so_luong = value;
					this.SendPropertyChanged("so_luong");
					this.Onso_luongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gia", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> gia
		{
			get
			{
				return this._gia;
			}
			set
			{
				if ((this._gia != value))
				{
					this.OngiaChanging(value);
					this.SendPropertyChanging();
					this._gia = value;
					this.SendPropertyChanged("gia");
					this.OngiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tong_tien", AutoSync=AutoSync.Always, DbType="Decimal(21,2)", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> tong_tien
		{
			get
			{
				return this._tong_tien;
			}
			set
			{
				if ((this._tong_tien != value))
				{
					this.Ontong_tienChanging(value);
					this.SendPropertyChanging();
					this._tong_tien = value;
					this.SendPropertyChanged("tong_tien");
					this.Ontong_tienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_do_day", DbType="Int")]
		public System.Nullable<int> do_day
		{
			get
			{
				return this._do_day;
			}
			set
			{
				if ((this._do_day != value))
				{
					this.Ondo_dayChanging(value);
					this.SendPropertyChanging();
					this._do_day = value;
					this.SendPropertyChanged("do_day");
					this.Ondo_dayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mau_sac", DbType="NVarChar(255)")]
		public string mau_sac
		{
			get
			{
				return this._mau_sac;
			}
			set
			{
				if ((this._mau_sac != value))
				{
					this.Onmau_sacChanging(value);
					this.SendPropertyChanging();
					this._mau_sac = value;
					this.SendPropertyChanged("mau_sac");
					this.Onmau_sacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="chi_tiet_san_pham_chi_tiet_hoa_don", Storage="_chi_tiet_san_pham", ThisKey="chi_tiet_san_pham_id", OtherKey="chi_tiet_id", IsForeignKey=true)]
		public chi_tiet_san_pham chi_tiet_san_pham
		{
			get
			{
				return this._chi_tiet_san_pham.Entity;
			}
			set
			{
				chi_tiet_san_pham previousValue = this._chi_tiet_san_pham.Entity;
				if (((previousValue != value) 
							|| (this._chi_tiet_san_pham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._chi_tiet_san_pham.Entity = null;
						previousValue.chi_tiet_hoa_dons.Remove(this);
					}
					this._chi_tiet_san_pham.Entity = value;
					if ((value != null))
					{
						value.chi_tiet_hoa_dons.Add(this);
						this._chi_tiet_san_pham_id = value.chi_tiet_id;
					}
					else
					{
						this._chi_tiet_san_pham_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("chi_tiet_san_pham");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hoa_don_chi_tiet_hoa_don", Storage="_hoa_don", ThisKey="hoa_don_id", OtherKey="hoa_don_id", IsForeignKey=true)]
		public hoa_don hoa_don
		{
			get
			{
				return this._hoa_don.Entity;
			}
			set
			{
				hoa_don previousValue = this._hoa_don.Entity;
				if (((previousValue != value) 
							|| (this._hoa_don.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._hoa_don.Entity = null;
						previousValue.chi_tiet_hoa_dons.Remove(this);
					}
					this._hoa_don.Entity = value;
					if ((value != null))
					{
						value.chi_tiet_hoa_dons.Add(this);
						this._hoa_don_id = value.hoa_don_id;
					}
					else
					{
						this._hoa_don_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("hoa_don");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
